# Generated by Django 2.2.1 on 2019-05-13 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPokemon', '0002_moledopesquisa'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MoledoPesquisa',
            new_name='ModeloPesquisa',
        ),
    ]
