# Generated by Django 2.2.1 on 2019-05-14 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPokemon', '0003_auto_20190512_2348'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Local',
        ),
        migrations.DeleteModel(
            name='ModeloPesquisa',
        ),
    ]
