# Generated by Django 2.2.1 on 2019-05-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appPokemon', '0004_auto_20190513_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloPesquisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=100)),
            ],
        ),
    ]
