# Generated by Django 2.2.1 on 2019-05-14 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPokemon', '0005_modelopesquisa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModeloPesquisa',
        ),
    ]
